[protocol]
version = "1.0.0"
hard_reset = false
activation_point = "2022-02-23T20:06:38.035565Z"

[network]
name = "casper-net-1"
maximum_net_message_size = 23068672

[core]
era_duration = "41seconds"
minimum_era_height = 10
validator_slots = 10
auction_delay = 3
locked_funds_period = "90days"
unbonding_delay = 14
round_seigniorage_rate = [ 15959, 6204824582392,]
max_associated_keys = 100
max_runtime_call_stack_height = 12

[highway]
finality_threshold_fraction = [ 1, 3,]
minimum_round_exponent = 13
maximum_round_exponent = 14
reduced_reward_multiplier = [ 1, 5,]

[deploys]
max_payment_cost = "0"
max_ttl = "1day"
max_dependencies = 10
max_block_size = 10485760
max_deploy_size = 1048576
block_max_deploy_count = 100
block_max_transfer_count = 1000
block_gas_limit = 10000000000000
payment_args_max_length = 1024
session_args_max_length = 1024
native_transfer_minimum_motes = 2500000000

[wasm]
max_memory = 64
max_stack_height = 188

[system_costs]
wasmless_transfer_cost = 100000000

[wasm.storage_costs]
gas_per_byte = 630000

[wasm.opcode_costs]
bit = 300
add = 210
mul = 240
div = 320
load = 2500
store = 4700
const = 110
local = 390
global = 390
control_flow = 440
integer_comparison = 250
conversion = 420
unreachable = 270
nop = 200
current_memory = 290
grow_memory = 240000
regular = 210

[system_costs.auction_costs]
get_era_validators = 10000
read_seigniorage_recipients = 10000
add_bid = 10000
withdraw_bid = 10000
delegate = 10000
undelegate = 10000
run_auction = 10000
slash = 10000
distribute = 10000
withdraw_delegator_reward = 10000
withdraw_validator_reward = 10000
read_era_id = 10000
activate_bid = 10000

[system_costs.mint_costs]
mint = 2500000000
reduce_total_supply = 10000
create = 2500000000
balance = 10000
transfer = 10000
read_base_round_reward = 10000

[system_costs.handle_payment_costs]
get_payment_purse = 10000
set_refund_purse = 10000
get_refund_purse = 10000
finalize_payment = 10000

[system_costs.standard_payment_costs]
pay = 10000

[wasm.host_function_costs.add]
cost = 5800
arguments = [ 0, 0, 0, 0,]

[wasm.host_function_costs.add_associated_key]
cost = 9000
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.add_contract_version]
cost = 200
arguments = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.blake2b]
cost = 200
arguments = [ 0, 0, 0, 0,]

[wasm.host_function_costs.call_contract]
cost = 4500
arguments = [ 0, 0, 0, 0, 0, 420, 0,]

[wasm.host_function_costs.call_versioned_contract]
cost = 200
arguments = [ 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.create_contract_package_at_hash]
cost = 200
arguments = [ 0, 0,]

[wasm.host_function_costs.create_contract_user_group]
cost = 200
arguments = [ 0, 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.create_purse]
cost = 2500000000
arguments = [ 0, 0,]

[wasm.host_function_costs.disable_contract_version]
cost = 200
arguments = [ 0, 0, 0, 0,]

[wasm.host_function_costs.get_balance]
cost = 3800
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.get_blocktime]
cost = 330
arguments = [ 0,]

[wasm.host_function_costs.get_caller]
cost = 380
arguments = [ 0,]

[wasm.host_function_costs.get_key]
cost = 2000
arguments = [ 0, 440, 0, 0, 0,]

[wasm.host_function_costs.get_main_purse]
cost = 1300
arguments = [ 0,]

[wasm.host_function_costs.get_named_arg]
cost = 200
arguments = [ 0, 0, 0, 0,]

[wasm.host_function_costs.get_named_arg_size]
cost = 200
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.get_phase]
cost = 710
arguments = [ 0,]

[wasm.host_function_costs.get_system_contract]
cost = 1100
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.has_key]
cost = 1500
arguments = [ 0, 840,]

[wasm.host_function_costs.is_valid_uref]
cost = 760
arguments = [ 0, 0,]

[wasm.host_function_costs.load_named_keys]
cost = 42000
arguments = [ 0, 0,]

[wasm.host_function_costs.new_uref]
cost = 17000
arguments = [ 0, 0, 590,]

[wasm.host_function_costs.print]
cost = 20000
arguments = [ 0, 4600,]

[wasm.host_function_costs.provision_contract_user_group_uref]
cost = 200
arguments = [ 0, 0, 0, 0, 0,]

[wasm.host_function_costs.put_key]
cost = 38000
arguments = [ 0, 1100, 0, 0,]

[wasm.host_function_costs.read_host_buffer]
cost = 3500
arguments = [ 0, 310, 0,]

[wasm.host_function_costs.read_value]
cost = 6000
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.read_value_local]
cost = 5500
arguments = [ 0, 590, 0,]

[wasm.host_function_costs.remove_associated_key]
cost = 4200
arguments = [ 0, 0,]

[wasm.host_function_costs.remove_contract_user_group]
cost = 200
arguments = [ 0, 0, 0, 0,]

[wasm.host_function_costs.remove_contract_user_group_urefs]
cost = 200
arguments = [ 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.remove_key]
cost = 61000
arguments = [ 0, 3200,]

[wasm.host_function_costs.ret]
cost = 23000
arguments = [ 0, 420000,]

[wasm.host_function_costs.revert]
cost = 500
arguments = [ 0,]

[wasm.host_function_costs.set_action_threshold]
cost = 74000
arguments = [ 0, 0,]

[wasm.host_function_costs.transfer_from_purse_to_account]
cost = 2500000000
arguments = [ 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.transfer_from_purse_to_purse]
cost = 82000
arguments = [ 0, 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.transfer_to_account]
cost = 2500000000
arguments = [ 0, 0, 0, 0, 0, 0, 0,]

[wasm.host_function_costs.update_associated_key]
cost = 4200
arguments = [ 0, 0, 0,]

[wasm.host_function_costs.write]
cost = 14000
arguments = [ 0, 0, 0, 980,]

[wasm.host_function_costs.write_local]
cost = 9500
arguments = [ 0, 1800, 0, 520,]
